version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: juliakut/progrtech:django-compose
    container_name: django
    networks:
      - public
    ports:
      - 8000:8000
  monitor:
    build:
      context: .
      dockerfile: Dockerfile.monit
    image: juliakut/progrtech:monitoring-compose
    container_name: monitoring
    networks:
      - public

networks:
  public:
    driver: bridge